### ISSUE TITLE
which version of tensorflow it should be?

### ISSUE THREAD

**Issue by loveJasmine** [SeoSangwoo/Attention-Based-BiLSTM-relation-extraction#1]
Writing to /Users//Attention-Based-BiLSTM-relation-extraction/runs/1526525946

Traceback (most recent call last):
  File "train.py", line 262, in <module>
    tf.app.run()
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 259, in main
    train(x_text, dist1, dist2, y, pos)
  File "train.py", line 246, in train
    train_step(x_batch, y_batch)
  File "train.py", line 202, in train_step
    feed_dict)

**Comment by WellBetter** [comment]
I used TensorFlow 1.8 ,it's  ok. 
If there is still can't work, maybe you can try change the code, `FLAGS._parse_flags()` ,on line 37 in train.py to `FLAGS.flag_values_dict()`.

**Comment by SeekPoint** [comment]
it works
