### ISSUE TITLE
when use python3 train.py I got a problem like this: " ValueError: Input 0 of layer dense_1 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank."

### ISSUE THREAD

**Issue by Alucardmini** [SeoSangwoo/Attention-Based-BiLSTM-relation-extraction#15]
Train/Dev split: 7200/800

Traceback (most recent call last):
  File "/Users/wuxikun/Downloads/Attention-Based-BiLSTM-relation-extraction-master/train.py", line 162, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/Users/wuxikun/Downloads/Attention-Based-BiLSTM-relation-extraction-master/train.py", line 158, in main
    train()
  File "/Users/wuxikun/Downloads/Attention-Based-BiLSTM-relation-extraction-master/train.py", line 61, in train
    l2_reg_lambda=FLAGS.l2_reg_lambda)
  File "/Users/wuxikun/Downloads/Attention-Based-BiLSTM-relation-extraction-master/att_lstm.py", line 49, in __init__
    self.logits = tf.layers.dense(self.h_drop, num_classes, kernel_initializer=initializer())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 253, in dense
    return layer.apply(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 762, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 629, in __call__
    self._assert_input_compatibility(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1122, in _assert_input_compatibility
    self.name + ' is incompatible with the layer: '
ValueError: Input 0 of layer dense_1 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

Process finished with exit code 1

I guess it cause by the function attention(inputs) which return an output with unknown shape, how can I fix it ? or would you please tell me my mistaken ?

**Comment by PeterBOYYY** [comment]
problem will be solved if you try this way

self.h_drop=tf.reshape(self.h_drop,[-1,hidden_size])

**Comment by grapeff** [comment]
My program has also get this bug,  so how did you solve the problem? how can I fix it ?
